### ISSUE TITLE
RuntypeUsageError: boolean literals inside a union

### ISSUE THREAD

**Issue by taosx** [hoeck/simple-runtypes#98]
I believe I've found a bug adding boolean literals inside a union, ex.:

```ts
import * as st from 'simple-runtypes';
const d = st.union(st.record({ d: st.literal(false) }), st.record({ d: st.literal(true) }));
```

At runtime I get the following error in logs
```
257 | 
258 | var RuntypeUsageError = /*#__PURE__*/function (_Error2) {
259 |   _inheritsLoose(RuntypeUsageError, _Error2);
260 | 
261 |   function RuntypeUsageError() {
262 |     return _Error2.apply(this, arguments) || this;
               ^
error: broken record type definition, function (v, failOrThrow) {
```

<details>
  <summary>Complete error</summary>

```
257 | 
258 | var RuntypeUsageError = /*#__PURE__*/function (_Error2) {
259 |   _inheritsLoose(RuntypeUsageError, _Error2);
260 | 
261 |   function RuntypeUsageError() {
262 |     return _Error2.apply(this, arguments) || this;
               ^
error: broken record type definition, function (v, failOrThrow) {
    if (typeof v !== "object" || Array.isArray(v) || v === null)
      return createFail(failOrThrow, "expected an object", v);
    var o = v;
    var res = isPure ? o : {};
    for (var i = 0;i < typemapKeys.length; i++) {
      var k = typemapKeys[i];
      var t = typemapValues[i];
      var value = t(o[k], failSymbol);
      if (isFail(value)) {
        if (!(k in o))
          return createFail(failOrThrow, "missing key in record: " + debugValue(k));
        return propagateFail(failOrThrow, value, v, k);
      }
      if (!isPure)
        res[k] = value;
    }
    if (!sloppy) {
      var unknownKeys = [];
      for (var _k in o)
        if (!Object.prototype.hasOwnProperty.call(typemap, _k))
          unknownKeys.push(_k);
      if (unknownKeys.length)
        return createFail(failOrThrow, "invalid keys in record: " + debugValue(unknownKeys), v);
    }
    return res;
  }[d] must be a string or number, not false
      at new RuntypeUsageError (/home/runner/GainsboroDismalDiscussion/node_modules/.pnpm/simple-runtypes@7.1.3/node_modules/simple-runtypes/dist/simple-runtypes.esm.js:262:11)
      at /home/runner/GainsboroDismalDiscussion/node_modules/.pnpm/simple-runtypes@7.1.3/node_modules/simple-runtypes/dist/simple-runtypes.esm.js:1128:12
      at internalDiscriminatedUnion (/home/runner/GainsboroDismalDiscussion/node_modules/.pnpm/simple-runtypes@7.1.3/node_modules/simple-runtypes/dist/simple-runtypes.esm.js:1119:2)
      at /home/runner/GainsboroDismalDiscussion/index.ts:11:10
```
</details>

**Comment by hoeck** [comment]
Thanks for reporting this.

The code that tries to figure out the type-discriminator field is quite primitive. It only looks for fields that are common across all record definitions of the union and then assumes that they are strings or numbers.

Needs to be fixed for sure, I'll look into it.
